---
title: "Arabidopsis - regressions"
author: "Nelson Nazzicari"
date: "`r Sys.Date()`"
output: 
  html_document:
    css: CREA.css
    toc: true
    toc_float: true
    number_sections: true
---

```{r setup, echo=FALSE, include=FALSE, message=FALSE}
library(knitr)
options(knitr.kable.NA = ' ', digits = 3) #this is for kable
library(ggplot2)
library(plyr)
library(printr)
library(DT)
library(xfun)
xfun::pkg_load2(c('base64enc', 'htmltools', 'mime'))
```

```{r cheatsheet, echo=FALSE, include=FALSE, eval=FALSE}
# EVALUATE CODE?  eval=TRUE
# PRINT CODE?     echo=TRUE
# PRINT OUTPUT?   include=TRUE
# UNWANTED STUFF? message=FALSE warning=FALSE error=FALSE

#attach a file (e.g. an xls)
xfun::embed_file('some_file.xls')

#data table with fancy selectors and searches
DT::datatable(cars)

#more humble data table
kable(cars, caption = "my cars")


```

```{r echo=FALSE, include=TRUE}
#this is your standard R chunk
```

# Document history

<!--
To highlight changes use
<span class="new"> your stuff </span>
-->

* 202x-xx-xx - initial report

# Aim
Some foreword describing the report

# Dataset
Data available

# Analysis & results
You decide if this needs to be split in two or more parts


